[build]
  command = "node export-notion-data.js && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."ask"]
  timeout = 26

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
